### ISSUE TITLE
【ユーザー貢献度機能】回答にいいね！した時にquestion_idが入っていない

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#123]
回答にいいね！した時にデータベース上、question_idが入っていない

[1] pry(main)> Vote.all
=>#<Vote:0x007fcc63a2cd58
  id: 10,
  user_id: 2,
  question_id: nil,　⬅️
  answer_id: 4,
  plus_or_minus: 0,
  created_at: Thu, 31 Aug 2017 01:49:26 UTC +00:00,
  updated_at: Thu, 31 Aug 2017 01:49:26 UTC +00:00>,

**Comment by ikedakohei** [comment]
レビューありがとうございます！

回答にいいね！したときにquesition_idとひもづけてしまうと、質問のいいね！と干渉をおこしてしまうため、あえてぬきました。issues/#123をローカルで動かしてみましたが、やはり同じでした。

question_idがnullだと不都合ありますか？？

**Comment by junkofujino** [comment]
ああ、なるほど！
answer_idも一意だから問題ないですね。
すみません。question_idとanswer_idセットで一意だと勘違いしてました💦
（ 同じanswer_idかぶると思ってました）

プルリク消します！

**Comment by ikedakohei** [comment]
はい！問題ないみたいです！
私もなんでこんなバグが起こるのだろうとずっと考えこんでしまいました。
こちらのissueクローズさせていただきますm(__)m
