### ISSUE TITLE
【ユーザー貢献度機能】投票ボタン実装方法検討

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#18]
・投票ボタンの実装方法調査・検討　→JS？
私も見えてません。厳しそうであれば、slackでみんなに相談してください。

ちなみにStackOverFlowの投票ボタンってどれ？って分からなかったのですが、数字の上下にある▲▼のことなんですね。
http://blog.jnito.com/entry/2015/10/04/073825

**Comment by ikedakohei** [comment]
こちらクローズしますね
