### ISSUE TITLE
【質問お気に入り機能】View作成

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#26]
・questions/show.html.erb かパーシャルファイルに実装することになると思います。
どこに書くかも検討の上、実装してください。
questions/show.html.erbは他の人とコンフリクトする可能性があるので、ご注意ください。

**Comment by kusano-lab** [comment]
views/favorites/（←※masterに間違ってpushしてます汗『対応中』）
・_favorite.btn.html.erb
・create.js.erb
・destroy.js.erb
・index.html.erb

questions/show.html.erb
・お気に入り登録ボタンの追加

routes.rb
・お気に入り一覧ページ追加
