### ISSUE TITLE
【ユーザー貢献度機能】routing、Model検討

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#27]
一応、私の方でrouting、model設定しましたが、これで良いかご検討ください。

◆routing
question_answer_votes POST   /questions/:question_id/answers/:answer_id/votes(.:format)     votes#create
question_answer_vote DELETE /questions/:question_id/answers/:answer_id/votes/:id(.:format) votes#destroy

◆model（一部省略）
  create_table "votes", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "question_id"
    t.integer  "answer_id"
    t.integer  "plus_or_minus", default: 0, null: false

◆迷った部分
・やりたい事は質問と回答にそれぞれ投票できるようにしたい。回答の時は、question_id、answer_idに値が入るから良いとして、質問の時はanswer_idはnilで良いか？（←データの持ち方としてはいまいち）
・nilとするとroutingはどうするのか。上記だとNGなので、質問から来た時と回答から来た時でroutingを分けるか。
・plusとminusの値の持ち方は「1」「-1」で良いか。→単純に足し算で欲しい結果が表示できるのでこれが良いかと思いました。
・plusとminusの値のデフォルトは0で良いか

**Comment by ikedakohei** [comment]
勉強になります！ありがとうございます！！
下記の理解であってますかね？？

userとvotesが１対多の関係。
questionとvotesが１対多の関係。
answerとvotesが１対多の関係。
一人のuserは一つのquestion（またはanswer）に対して、+1か0か-1しかポイントをつける事ができない（デフォルトは0）。
- https://github.com/nakayuu07/dive23-13/blob/master/app/models/vote.rb
↑`belongs_to :answer`を追加
- https://github.com/nakayuu07/dive23-13/blob/master/app/models/question.rb
↑`has_many :votes, dependent: :destroy`を追加
- https://github.com/nakayuu07/dive23-13/blob/master/app/models/user.rb
↑ `has_many :votes, dependent: :destroy`を追加
- https://github.com/nakayuu07/dive23-13/blob/master/app/models/answer.rb
↑`has_many :votes, dependent: :destroy`を追加

ルーティングに関しては、このままだと、answersが一つもない状態だと、エラーになるって事ですか？(answer_idがnilになるため)
```
  resources :questions do
    resources :answers do
      resources :votes, only: [:create, :destroy]
    end
    resources :favorites, only: [:create, :destroy]
  end
```

**Comment by junkofujino** [comment]
>userとvotesが１対多の関係。
>questionとvotesが１対多の関係。
>answerとvotesが１対多の関係。

はい。合ってます！

>一人のuserは一つのquestion（またはanswer）に対して、+1か0か-1しかポイントをつける事ができない（デフォルトは0）。

はい。ただ、ユーザの操作から来るのは+1か-1だけです。足し算する時にnilが良くないので、デフォルトを0に・・と思いましたが、デフォルト入るケースがないかも。。default: 0, は外して良い気がしてきました。

>- https://github.com/nakayuu07/dive23-13/blob/master/app/models/vote.rb
↑`belongs_to :answer`を追加

belongs_to はanswer_idがnilでも許容してくれるのか気になりました（調べてません）

>- https://github.com/nakayuu07/dive23-13/blob/master/app/models/question.rb
↑`has_many :votes, dependent: :destroy`を追加
>- https://github.com/nakayuu07/dive23-13/blob/master/app/models/user.rb
↑ `has_many :votes, dependent: :destroy`を追加
>- https://github.com/nakayuu07/dive23-13/blob/master/app/models/answer.rb
↑`has_many :votes, dependent: :destroy`を追加

合ってると思います！

>ルーティングに関しては、このままだと、answersが一つもない状態だと、エラーになるって事ですか？(answer_idがnilになるため)

answerテーブルにデータがあるかどうかではなく、質問に対して投票する時、answer_idはセットできないですよね？(回答に対して投票する時はquestion_idもanswer_idもセットできる）
なので、nilになっちゃうけどいいのかな、って話です。

私がいま思いつく対応案としては、
1) 質問から飛んで来た時は、nilにする。ただし、routingエラーになるので、質問から来た時と回答から来た時でroutingを分ける。質問から来た時は、以下のroutingにする
　question_votes POST /questions/:question_id/votes(.:format) votes#create
　question_vote DELETE /questions/:question_id/votes/:id(.:format) votes#destroy
2) 質問から飛んで来た時は、answer_idに'aaa', '***' のようなダミーコードをセットする。

他にもっといい方法があるかもしれませんので、調べてみてくださいm(_ _)m

**Comment by ikedakohei** [comment]
> belongs_to はanswer_idがnilでも許容してくれるのか気になりました（調べてません）

question_idのみですむ場合とanswer_idが必要となる場合(if文)とで、votesの扱いを分ければよい気がしました。if文使わなくてもよいのかもしれませんが。

>```
>　question_votes POST /questions/:question_id/votes(.:format) votes#create
>　question_vote DELETE /questions/:question_id/votes/:id(.:format) votes#destroy
>```
↑のルーティングで、answer_idがnilかどうかは関係なくなると思います。quesitonにvoteが投票される場合とanswerにvoteが投票される場合とで、処理を分けるみたいな感じでなんとかなってくれないかと。。

> はい。ただ、ユーザの操作から来るのは+1か-1だけです。足し算する時にnilが良くないので、デフォルトを0に・・と思いましたが、デフォルト入るケースがないかも。。default: 0, は外して良い気がしてきました。

投票をしていない状態で、voteの数字を表示させる時にデフォルトで0であると便利だと思います。また、最初の時以外でも、0が入るケースはあってもよいかもしれません。一回+1になるクリックイベントを起こすとします。でも、やっぱり+1にも-1にもしたくないなって時に、-1になるクリックイベントを起こします。その結果、0になります。みたいな…
そうすれば、単純な足し算と引き算で実装できそうな気がして…実際作業してみないとわからないですが…

変な事言ってたらすみません。。というか、自分で調べます。無理だとなったらみなさんに相談させて頂きます。ありがとうございました！

**Comment by ikedakohei** [comment]
plus_minusは計算にしか使わないから+1と-1しかいらないですね。。m(__)m

**Comment by junkofujino** [comment]
ですね！
ユーザの操作で▲押した時は+1, ▼押した時は-1を設定、だけで良さそうですね。
▲か▼を2回続けて押したらそのデータ削除するのかと思ったらそうでもなさそうなのでdestroyも不要？
(本物のstackoverflowで確認したかったのですが、信頼度が15点以下のユーザは結果に反映されないみたいですorz)

**Comment by junkofujino** [comment]
>↑のルーティングで、answer_idがnilかどうかは関係なくなると思います。quesitonにvoteが投票される場合とanswerにvoteが投票される場合とで、処理を分けるみたいな感じでなんとかなってくれないかと。。

そうですね。
URLパスと別にviewのボタンからcontrollerにパラメータ渡すってことですよね？
　view
　 質問画面のボタン→　'question'などのフラグ
　 回答画面のボタン→　'answer'などのフラグ、answer_id
　※上記実際は同じhtmlファイルになるかと思います

　controller　#create
     if文で切り分け。'question'が来た時はanswer_idはnil、'answer'が来た時は渡されたanswer_idをセット

ご提案の方法でやってみて頂けますか？うまく行かなかったらまた考えましょう。

**Comment by ikedakohei** [comment]
voteの集計値をとるときに、N+1問題について考慮する必要ある気がしました。
N+1問題をほとんど理解できていませんが。。
とりあえず、手を動かしてみます！ありがとうございます。
