### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kusano-lab** [nakayuu07/dive23-13#31]
・questions/show.html.erb かパーシャルファイルに実装することになると思います。
どこに書くかも検討の上、実装してください。
questions/show.html.erbは他の人とコンフリクトする可能性があるので、ご注意ください。

**Comment by junkofujino** [comment]
これcloseしてますが、まだじゃないでしょうか？

**Comment by kusano-lab** [comment]
このissueはassignできるかちょっとテストしたときに作成したもので
オリジナルは#26のものです。（消し方がわからず...とりあえずcloseしてます）
紛らわしくなってしまい、申し訳ないですm(. .)m

**Comment by junkofujino** [comment]
そうなんですね。
なぜか【質問お気に入り機能】View作成 #31がcloseされてたので、reopenしました！

**Comment by junkofujino** [comment]
あ、意味が分かりました！
調べましたが、issueの削除はできないみたいですね。紛らわしいので、タイトルを変更しました。

**Comment by kusano-lab** [comment]
タイトルを変更すれば、紛らわしくないですね！
ありがとうございます！
