### ISSUE TITLE
【Bug対応】マイグレーションできない

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#51]
【現象】
rake db:migrateで以下のエラー発生

The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

【対応方法】
https://teratail.com/questions/82468
gemを
gem 'pg'
から
gem 'pg', '~> 0.20.0'
に変更で解消

**Comment by ikedakohei** [comment]
' が ‘になっているみたいです。

**Comment by junkofujino** [comment]
修正しました！

**Comment by ikedakohei** [comment]
確認不足すみませんでした！
