### ISSUE TITLE
【質問お気に入り機能】お気に入りボタン有効化

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#54]
お気に入りボタンを押しても何も反応（色が変わったり）してないようです。
ご確認お願いします。

**Comment by kusano-lab** [comment]
お気に入りボタンの件、了解しました。
外出してるため、対応は夜頃になりそうです。
ちなみに、問題なければ、文言が変わります！

**Comment by junkofujino** [comment]
はい。文言変えて頂いて構いません。
よろしくお願いします！

**Comment by kusano-lab** [comment]
お気に入りボタンが動作しない件、確認しましたところ
モデルの設定に関する処理をpushし忘れていました。
お手数おかけしてすみません💦

対応しましたご確認よろしくお願いします！

**Comment by junkofujino** [comment]
有効化されてるの確認しました。ありがとうございます！

**Comment by kusano-lab** [comment]
確認ありがとうございました！
