### ISSUE TITLE
【質問お気に入り機能】お気に入り一覧ページ作成

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#55]
お気に入りページ（http://localhost:3000/favorites)でタイトル以外何も表示されてないようです。
こちらもご確認お願いします。

**Comment by kusano-lab** [comment]
こちらは、お気に入り登録してない状態だと何も表示されないからだと思います。
お気に入り登録ボタン修正までお待ちください！m(._.)m

**Comment by junkofujino** [comment]
お気に入り一覧ページも正しく表示されていることを確認しました。

**Comment by kusano-lab** [comment]
こちらも確認いただき、ありがとうございます！
