### ISSUE TITLE
レビュー用

### ISSUE THREAD

**Issue by timeshiftseiya** [nakayuu07/dive23-13#64]

**Comment by timeshiftseiya** [comment]
- model
  - 削除後のデータのあり方を意識できているのが良い
  - answer_model
    - has_many :votes, dependent: :destroy関連したところが同時に削除されるようになっているのが良い
  - favorite_model
    - counter_cacheを使いカウントをすることでコードがスッキリして良い
    - default_scopeを使いコントローラでの記述を短くしているのが良い(使う場合は一緒に開発している人に共有が必要)
- controller
  - answers_controller.rb
    - buildを使い一行でインスタンスを作成しているところが良い
  - favorites_controller.rb
    - before_actionでアクションの制御をできているところが良い
    - @questions = Question.all allを使わずに本当に必要なデータだけを取得できればなおよくなります。
    - favorite = current_user.favorites.build(question_id: @question.id) question_idがわかればidを設定できるのであれば

- gemfile
  - better_errorsとpry-railsは基本的にdevelopmentで使う(何か本番で使う用途があるか確認)
   - 不要なコメントは削除
- public
  - https://github.com/nakayuu07/dive23-13/tree/master/public/uploads/user/avatar/13
  - この画像は必要か確認
- migratioin
  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170823114141_add_user_id_toquestions.rb
  - toの後はアンダースコアがあったほうがよい(統一感がある)
  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824031112_create_votes.rb
  - plus_or_minusで数字が入るとは思わない人もいるかと思うのでvoteの評価の数値を表すものが良いと思う
  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824122425_create_tags.rb
  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824122425_create_tags.rb
  - commitの名前から何の作業したか判断できない

**Comment by timeshiftseiya** [comment]
![2017-08-26 15 24 18](https://user-images.githubusercontent.com/16096244/29739189-b37c6b74-8a72-11e7-8f3e-b6d14facc77b.png)
プロフィールに何を書けばいいかわからない

**Comment by timeshiftseiya** [comment]
- userとfavoriteの繋がりがないのでbuildをする時にエラー(お気に入り追加)
- answerを編集するactionがないためエラー

メモ終了

**Comment by junkofujino** [comment]
宮岡さん、レビューありがとうございます。


>  - favorite_model
>    - counter_cacheを使いカウントをすることでコードがスッキリして良い
>    - default_scopeを使いコントローラでの記述を短くしているのが良い(使う場合は一緒に開発している人に共有が必要)

counter_cache、default_scope使うのやめてしまいました。問題ありますでしょうか？


>  - favorites_controller.rb
>    - @questions = Question.all allを使わずに本当に必要なデータだけを取得できればなおよくなります。

修正しました。


   >- favorite = current_user.favorites.build(question_id: @question.id) question_idがわかればidを設定できるのであれば

すみません。こちらの意味が分かりませんでしたが、(question_id: @question.id)にparamsを使えるのでは？と言う話でしょうか？


>- gemfile
>  - better_errorsとpry-railsは基本的にdevelopmentで使う(何か本番で使う用途があるか確認)
>   - 不要なコメントは削除

修正しました。


>- public
>  - https://github.com/nakayuu07/dive23-13/tree/master/public/uploads/user/avatar/13
>  - この画像は必要か確認

開発中のブランチに含まれているので、そのままpushすると含まれてしまうと思いますが、こういうのは開発手順としてどうするべきでしょうか？例えば、push前に外す、.gitignoreに記載する、など。


>- migratioin
>  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170823114141_add_user_id_toquestions.rb
>  - toの後はアンダースコアがあったほうがよい(統一感がある)

修正しました。


>  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824031112_create_votes.rb
>  - plus_or_minusで数字が入るとは思わない人もいるかと思うのでvoteの評価の数値を表すものが良いと思う

これは列名が適切でないという話でしょうか？最初に頂いたE-R図がそうなってたのですが、必要であれば修正いたします。

>  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824122425_create_tags.rb
>  - https://github.com/nakayuu07/dive23-13/blob/master/db/migrate/20170824122425_create_tags.rb
>  - commitの名前から何の作業したか判断できない
 
 これは統一ルールを決めた方が良いですね。


>プロフィールに何を書けばいいかわからない

placeholder設定して、入力欄も大きくしました。


>userとfavoriteの繋がりがないのでbuildをする時にエラー(お気に入り追加)

別issueで修正済です。


>answerを編集するactionがないためエラー

別issueで対応します。

**Comment by timeshiftseiya** [comment]
https://github.com/thoughtbot/shoulda-matchers
