### ISSUE TITLE
【質問お気に入り機能】自分のお気に入り一覧ページの作成

### ISSUE THREAD

**Issue by junkofujino** [nakayuu07/dive23-13#77]
> ・質問お気に入り機能
> お気に入りのランキングがある
> 自分のお気に入り一覧ページがある

機能要件を見ると、「お気に入りランキング」とは別に「自分のお気に入り一覧ページ」というのが必要なようです。

イメージ
お気に入りランキング
https://ja.stackoverflow.com/?tab=hot
自分のお気に入り一覧ページ
https://ja.stackoverflow.com/users/25015/kagura?tab=favorites

**Comment by kusano-lab** [comment]
自分のお気に入りページがほぼできました。

１箇所、わからない部分があり、ご教示もらえたら嬉しいです。

昨日の宮岡さんのレビューにありました
favorites_controller.rb内で必要な情報のみ取得する処理について、修正後どのような処理を行っているのか教えていただけないでしょうか。

「自分のお気に入り一覧」同じような処理を追加しないといけないのですが、いまいちわからない状態で。。。

わからない箇所はwhereの[ ]の意味と、keysとかの部分です！

現状、「自分のお気に入り一覧」ページのコードでは
とりあえず、@questions = Question.allみたいな感じで取得してます💦
[https://github.com/nakayuu07/dive23-13/blob/issues/%2377/app/controllers/users_controller.rb](url)

よろしくお願いします！

**Comment by junkofujino** [comment]
遅くなりました。

keysはハッシュで使えるメソッドです。@favoritesがハッシュなので。
http://qiita.com/kidach1/items/651b5b5580be40ad047e

![keys](https://user-images.githubusercontent.com/13149556/29748507-2fa65698-8b53-11e7-8749-e51d7ec757e0.png)

Questionから全件取得するのではなく、@favoritesにkey（question_id）があるデータだけ拾いたかったのでこうしています。

例えば、 質問が3つあって、1番目はお気に入りが2件、2番目は0、3番目は1件だった場合、
@favorites => {1=>2, 3=>1}
[@favorites.keys]は[1, 3]
になります。

**Comment by junkofujino** [comment]
一方、@favorites.keysで返ってきた結果は配列になります。

whereメソッドで複数の値を指定する場合、配列にする必要があるようです。
http://qiita.com/merrill/items/8ec158953cb4c2715c7b

![where](https://user-images.githubusercontent.com/13149556/29748569-2afe732c-8b54-11e7-949d-3560f04c1667.png)
